---
title: "<br>Titulo"
date: |-
  `r paste("<br> Ultima actualización:",format(Sys.Date(), "%d-%m-%Y"))`
output: 
  html_document:
        theme: cerulean
        toc: true
        toc_float: true
        toc_depth: 3
        collapsed: false
        smooth_scroll: false
        number_sections: false
        css: "rmd/resources/styles.css"
        includes:
          in_header: "rmd/resources/header.html"
---




```{r setup, include=FALSE}

## packages

load_packages(knitr, rmdformats, lorem)


## global options

options(max.print="75")

opts_chunk$set(echo=FALSE,
	             cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               width=75)

## devs

source("rmd/resources/info.R")

```

```{r icon}

htmltools::img(src = knitr::image_uri("rmd/resources/icono.png"), 
               alt = "logo", 
               style = "position:absolute; top:55px; right:-10px; padding:10px; width: 110px; height: 110px")

```

<br>


## Header 1

<br>

<div align="justify">

`r lorem::ipsum(paragraphs = 2)`

</div>


<br>


```{r, child="rmd/report.Rmd"}

```




## {.unlisted .unnumbered}

<div align="center" class="dev">

**Developers**: `r Developers`

**Maintainers**: `r Maintainers`

**® Cienfi `r Year`.**

</div>
        
           
